# Study 2: Real-world analysis

In [45]:
import numpy as np
import pandas as pd
pd.set_option('future.no_silent_downcasting', True)

import scipy.stats as sp
import statsmodels.api as sm
import statsmodels.formula.api as smf

import plotly.express as px
import plotly.graph_objects as go

from utils.utils import *
from utils.variables import *

## Read in data

In [46]:
# Get CTRS data to show classifier performance on experimental data
df_pids, df_ctrs, df_general, df_comparisons = retrieve_analysed_data('clinicians')

print('----------------------------------------------------------------')

# Get real world data
df_rw_pids, df_rw_ctrs, df_rw_clinical, df_rw_human_labels, df_rw_feedback = retrieve_realworld_data()

df_rw_pids['pid'] = df_rw_pids['pid'].astype(str)
df_rw_clinical['pid'] = df_rw_clinical['pid'].astype(str)

Removing 7 transcripts that are not appropriate for CBT
N = 227

condition        model
cognitive_layer  claude    25
                 gemini    26
                 gpt4      26
                 llama     24
human_therapist  human     26
standalone_llms  claude    25
                 gemini    24
                 gpt4      27
                 llama     24
dtype: int64

----------------------------------------------------------------
N users = 16630
N transcripts = 51916
N transcripts with autograded CTRS scores = 19674
N users with clinical outcomes = 942
N transcripts with human labels = 128
N transcripts with feedback = 6553

## CTRS Classifier

### Validation against experimental data

In [51]:
df = df_ctrs.copy()
df['human_score'] = df[['human1_score', 'human2_score']].apply(lambda x: x.dropna().iloc[0] if x.isna().sum() == 1 else x.mean(), axis=1)

df = (
    df
    .groupby('pid')[['human_score','classifier_score']]
    .mean()
    .reset_index()
    .dropna()
    .reset_index(drop=True)
)

print(f"N = {len(df)}")

compute_all_icc(df[['human_score','classifier_score']])

stat = sp.spearmanr(df[['human_score','classifier_score']])
print(f"Spearman's rho = {stat.correlation:.2f}, p = {readable_pvalue(stat.pvalue)}")

N = 227
Intraclass Correlation Coefficients (ICC) between human and classifier:
ICC(1,1): 0.464
ICC(1,k): 0.634
ICC(2,1): 0.519
ICC(2,k): 0.683
ICC(3,1): 0.654
ICC(3,k): 0.791
Spearman's rho = 0.71, p = 1.35e-35***

### Relationship to cognitive layer activation

Including curve-fitting procedure.

In [48]:
df = df_rw_pids.merge(df_rw_ctrs.drop(columns=['pid']),on='conversation_id',how='left')

mask = (df['n_user_messages']>=5) & (df['n_user_messages']<=30) & (df['n_characters']<5000)
df = df.loc[mask,].copy().reset_index(drop=True)

print(f"N users = {df['pid'].nunique()}")
print(f"N conversations = {df['conversation_id'].nunique()}")

df['z_ctrs_overall'] = zscore(df['ctrs_overall'])

# ------------------------------------------------------------------------------------------------------------------------------------
# Curve-fitting
# ------------------------------------------------------------------------------------------------------------------------------------

model_df = df.copy()

# Linear model
model_df['cl_transformed'] = model_df['cognitive_layer_score'].copy()
model_linear = smf.ols('z_ctrs_overall ~ cl_transformed + n_user_messages', data=model_df).fit()

# Log model
model_df['cl_transformed'] = model_df['cognitive_layer_score'].copy().apply(lambda x: np.log(x+1)   )
model_log = smf.ols('z_ctrs_overall ~ cl_transformed + n_user_messages', data=model_df).fit()

# Square root model
model_df['cl_transformed'] = model_df['cognitive_layer_score'].copy().apply(lambda x: np.sqrt(x))
model_sqrt = smf.ols('z_ctrs_overall ~ cl_transformed + n_user_messages', data=model_df).fit()

# Arctan model
model_df['cl_transformed'] = model_df['cognitive_layer_score'].copy().apply(lambda x: np.arctan(x))
model_arctan = smf.ols('z_ctrs_overall ~ cl_transformed + n_user_messages', data=model_df).fit()

# Hyperbolic model
model_df['cl_transformed'] = np.tanh(model_df['cognitive_layer_score']/model_df['cognitive_layer_score'].std())
model_hyperbolic = smf.ols('z_ctrs_overall ~ cl_transformed + n_user_messages', data=model_df).fit()

# Model comparison
model_comparison = pd.DataFrame({
    'model': ['linear', 'log', 'sqrt', 'arctan', 'hyperbolic'],
    'aic': [model_linear.aic, model_log.aic, model_sqrt.aic, model_arctan.aic, model_hyperbolic.aic],
    'bic': [model_linear.bic, model_log.bic, model_sqrt.bic, model_arctan.bic, model_hyperbolic.bic],
}).sort_values(by='bic',ascending=True)
model_comparison['bic_delta_next'] = model_comparison['bic'].diff()
model_comparison['bic_delta_best'] = model_comparison['bic'] - model_comparison['bic'].min()

print('Curve fitting model comparison:')
display(model_comparison)

# ------------------------------------------------------------------------------------------------------------------------------------
# Model
# ------------------------------------------------------------------------------------------------------------------------------------

model_df = df.copy()
model_df['z_cl'] = zscore(model_df['cognitive_layer_score'].apply(lambda x: np.sqrt(x)))

model = smf.ols('z_ctrs_overall ~ z_cl + n_user_messages', data=model_df).fit()
print_title('Sqrt cognitive layer score vs classified ctrs score')

print(f"β = {model.params['z_cl']:.2f}, 95% CI = [{model.conf_int().loc['z_cl',0]:.2f}, {model.conf_int().loc['z_cl',1]:.2f}], P = {readable_pvalue(model.pvalues['z_cl'])}")

# ------------------------------------------------------------------------------------------------------------------------------------
# Plot
# ------------------------------------------------------------------------------------------------------------------------------------

fig = px.scatter(
    df,
    x='cognitive_layer_score',
    y='z_ctrs_overall',
    title=f'Cognitive Layer Activation vs CTRS',
    width=400,
    height=400,
    opacity=0.1,
    template='simple_white',
    labels={'z_ctrs_overall': 'Scaled CTRS', 'cognitive_layer_score': 'Cognitive Layer Activation'},
    color_discrete_sequence=['#EF5DA8'],
)
fig.update_layout(showlegend=False, coloraxis_showscale=False, font={'family': 'Arial'})
fig.update_xaxes(range=[2,41])

model_df = df.copy()
model_df['sqrt_cl'] = np.sqrt(model_df['cognitive_layer_score'])
model_sqrt = smf.ols('z_ctrs_overall ~ sqrt_cl + n_user_messages', data=model_df).fit()

curve_df = pd.DataFrame({
    'cognitive_layer_score': [x for x in range(2,41)],
    'n_user_messages': [model_df['n_user_messages'].mean()] * 39
    })
curve_df['sqrt_cl'] = np.sqrt(curve_df['cognitive_layer_score'])
curve_df['z_ctrs_overall'] = model_sqrt.predict(curve_df[['sqrt_cl','n_user_messages']])

fig.add_trace(
    go.Scatter(
        x=curve_df['cognitive_layer_score'].values,
        y=curve_df['z_ctrs_overall'].values,
        mode='lines',
        line=dict(shape='spline', color='#000000', width=2),
        showlegend=False
    )
)

fig.show()

fig.write_image('../results/real_world_ctrs_cl_activation.svg',width=400,height=400)

N users = 8920
N conversations = 19674
Curve fitting model comparison:

        model           aic           bic  bic_delta_next  bic_delta_best
2        sqrt  52282.403314  52306.064474             NaN        0.000000
1         log  52330.184988  52353.846147       47.781674       47.781674
0      linear  52591.676127  52615.337286      261.491139      309.272813
3      arctan  53703.819830  53727.480990     1112.143704     1421.416516
4  hyperbolic  54474.124956  54497.786116      770.305126     2191.721642

===================================================================================================
SQRT COGNITIVE LAYER SCORE VS CLASSIFIED CTRS SCORE
===================================================================================================
β = 0.66, 95% CI = [0.64, 0.68], P = 0.00e+00***

### Supplementary: Controlling for initial state & conversation complexity

In [49]:
df = df_rw_pids.merge(df_rw_ctrs.drop(columns=['pid']),on='conversation_id',how='left')

mask = (df['n_user_messages']>=5) & (df['n_user_messages']<=30) & (df['n_characters']<5000)
df = df.loc[mask,].copy().reset_index(drop=True)

print(f"N users = {df['pid'].nunique()}")
print(f"N conversations = {df['conversation_id'].nunique()}")

df['z_ctrs_overall'] = zscore(df['ctrs_overall'])

# ------------------------------------------------------------------------------------------------------------------------------------
# Model
# ------------------------------------------------------------------------------------------------------------------------------------

control_vars = [
    'n_words_first_message',
    'n_sentences_first_message',
    'mean_words_first_3_messages',
    'mean_sentences_first_3_messages',
    'dictionary_complexity',
    'embedding_entropy',
    'sentiment_polarity'
]
control_var_string = ' + '.join(control_vars)

model_df = df.copy()
model_df['z_cl'] = zscore(model_df['cognitive_layer_score'].apply(lambda x: np.sqrt(x)))

model = smf.ols('z_ctrs_overall ~ z_cl + n_user_messages + ' + control_var_string, data=model_df).fit()
print_title('Sqrt cognitive layer score vs classified ctrs score')
print(model.summary())

print(f"β = {model.params['z_cl']:.2f}, 95% CI = [{model.conf_int().loc['z_cl',0]:.2f}, {model.conf_int().loc['z_cl',1]:.2f}], P = {readable_pvalue(model.pvalues['z_cl'])}")

N users = 8920
N conversations = 19674
===================================================================================================
SQRT COGNITIVE LAYER SCORE VS CLASSIFIED CTRS SCORE
===================================================================================================
                            OLS Regression Results
==============================================================================
Dep. Variable:         z_ctrs_overall   R-squared:                       0.221
Model:                            OLS   Adj. R-squared:                  0.221
Method:                 Least Squares   F-statistic:                     620.5
Date:                Mon, 22 Sep 2025   Prob (F-statistic):               0.00
Time:                        12:17:17   Log-Likelihood:                -25457.
No. Observations:               19674   AIC:                         5.093e+04
Df Residuals:                   19664   BIC:                         5.101e+04
Df Model:                           9
Covariance Type:            nonrobust
===================================================================================================
                                      coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
Intercept                           0.3911      0.040      9.719      0.000       0.312       0.470
z_cl                                0.6310      0.012     52.773      0.000       0.608       0.654
n_user_messages                    -0.1220      0.004    -28.458      0.000      -0.130      -0.114
n_words_first_message               0.0018      0.001      2.544      0.011       0.000       0.003
n_sentences_first_message          -0.0325      0.012     -2.803      0.005      -0.055      -0.010
mean_words_first_3_messages        -0.0293      0.003    -10.740      0.000      -0.035      -0.024
mean_sentences_first_3_messages     0.0152      0.016      0.966      0.334      -0.016       0.046
dictionary_complexity               0.0224      0.001     16.259      0.000       0.020       0.025
embedding_entropy                   0.0521      0.006      8.068      0.000       0.039       0.065
sentiment_polarity                 -0.1322      0.009    -14.836      0.000      -0.150      -0.115
==============================================================================
Omnibus:                      640.965   Durbin-Watson:                   1.886
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1196.351
Skew:                          -0.257   Prob(JB):                    1.64e-260
Kurtosis:                       4.094   Cond. No.                         326.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
β = 0.63, 95% CI = [0.61, 0.65], P = 0.00e+00***

### Supplementary: Validation against human labels

In [ ]:
df = (
    df_rw_human_labels
    .copy()
    .groupby('conversation_id')[['human_score','classifier_score']]
    .mean()
    .reset_index()
    .melt(id_vars='conversation_id',value_vars=['human_score','classifier_score'],var_name='rater',value_name='score')
    )
df['rater'] = df['rater'].apply(lambda x: x.split('_')[0])

df = df.merge(df_rw_pids[['conversation_id','cognitive_layer_score','n_user_messages']],on='conversation_id',how='left')

print(f"N transcripts = {df.loc[df['rater']=='human','conversation_id'].nunique()}")

# ------------------------------------------------------------------------------------------------------------------------------------
# Model
# ------------------------------------------------------------------------------------------------------------------------------------

model_df = df.loc[df['rater'] == 'human',].copy().reset_index(drop=True)

model_df['z_ctrs_overall'] = zscore(model_df['score'])
model_df['z_cl'] = zscore(model_df['cognitive_layer_score'])

model = smf.ols('z_ctrs_overall ~ z_cl + n_user_messages', data=model_df).fit()
print(model.summary())

print(f"β = {model.params['z_cl']:.2f}, 95% CI = [{model.conf_int().loc['z_cl',0]:.2f}, {model.conf_int().loc['z_cl',1]:.2f}], P = {readable_pvalue(model.pvalues['z_cl'])}")

N transcripts = 128
Intraclass Correlation Coefficients (ICC) between human and classifier:
ICC(1,1): 0.321
ICC(1,k): 0.486
ICC(2,1): 0.342
ICC(2,k): 0.509
ICC(3,1): 0.364
ICC(3,k): 0.534
Spearman's rho = 0.45, p = 1.24e-07***
                            OLS Regression Results
==============================================================================
Dep. Variable:         z_ctrs_overall   R-squared:                       0.204
Model:                            OLS   Adj. R-squared:                  0.191
Method:                 Least Squares   F-statistic:                     16.00
Date:                Mon, 22 Sep 2025   Prob (F-statistic):           6.52e-07
Time:                        12:17:23   Log-Likelihood:                -166.54
No. Observations:                 128   AIC:                             339.1
Df Residuals:                     125   BIC:                             347.6
Df Model:                           2
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept           0.1372      0.359      0.382      0.703      -0.573       0.848
z_cl                0.4787      0.108      4.448      0.000       0.266       0.692
n_user_messages    -0.0114      0.029     -0.392      0.696      -0.069       0.046
==============================================================================
Omnibus:                        2.598   Durbin-Watson:                   1.888
Prob(Omnibus):                  0.273   Jarque-Bera (JB):                2.637
Skew:                           0.326   Prob(JB):                        0.268
Kurtosis:                       2.737   Cond. No.                         58.6
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
β = 0.48, 95% CI = [0.27, 0.69], P = 1.89e-05***

## Clinical outcomes

### Cognitive layer score prediction

In [34]:
# Read in and filter data
df = df_rw_clinical.merge(
    df_rw_pids.groupby('pid')[['cognitive_layer_score','n_user_messages']].sum().reset_index(),on='pid',how='inner'
)

mask = (df['access_time_days']>=14)
n = df['pid'].nunique()
print(f"N participants = {n}")
n_exclude = df.loc[~mask,'pid'].nunique()
print(f"Excluding {n_exclude} participants who have fewer than 2 weeks between symptom measurements")

df = df.loc[mask,].copy().reset_index(drop=True)
print(f"N participants = {df['pid'].nunique()}")
print(f"--- NHS patients = {df.loc[df['source']=='nhs','pid'].nunique()}")
print(f"--- User research participants = {df.loc[df['source']=='user_research','pid'].nunique()}")

print(f'------ User research participants with 10+ weeks of data: {df.loc[(df["source"]=="user_research") & (df["access_time_days"]>=10*7),"pid"].nunique()}')

# Group by participant
df = df.groupby('pid').agg({
    'gad7_start': 'first',
    'phq9_start': 'first',
    'gad7_delta': 'first',
    'phq9_delta': 'first',
    'recovery': 'first',
    'cognitive_layer_score': 'sum',
    'n_user_messages': 'sum',
    'access_time_days': 'first',
    }).reset_index()

df['z_cl'] = zscore(np.sqrt(df['cognitive_layer_score']))
df['z_n_user_messages'] = zscore(df['n_user_messages']**2)

print(f"\nMedian time between symptom measurements = {df['access_time_days'].median():.2f} days ({df['access_time_days'].median()/7:.1f} weeks +/ {df['access_time_days'].std()/7:.1f})")

# Engagement metrics
engagement_df = (
    df_rw_pids
    .loc[df_rw_pids['pid'].isin(list(df['pid'].unique()))]
    .copy()
    .reset_index(drop=True)
)
engagement_df['n_exchanges'] = (engagement_df['n_user_messages'] * 2) + 1 # agent responds to each user message

n_conversations = engagement_df.groupby('pid')['conversation_id'].nunique().agg(['mean','std'])
print(f"N conversations per participant: M = {n_conversations['mean']:.1f}, SD = {n_conversations['std']:.1f}")

n_exchanges = engagement_df['n_exchanges'].agg(['mean','std'])
print(f"N exchanges per conversation: M = {n_exchanges['mean']:.1f}, SD = {n_exchanges['std']:.1f}, median = {engagement_df['n_exchanges'].median():.1f}")

# ------------------------------------------------------------------------------------------------------------------------------------
# Model
# ------------------------------------------------------------------------------------------------------------------------------------

# Symptom reduction
for outcome in ['gad7_delta','phq9_delta']:

    print_title(outcome)

    model = smf.ols(f'{outcome} ~ z_cl + z_n_user_messages + gad7_start + phq9_start', data=df).fit()
    print(model.summary())
    print(f"β = {model.params['z_cl']:.2f}, 95% CI = [{model.conf_int().loc['z_cl',0]:.2f}, {model.conf_int().loc['z_cl',1]:.2f}], P = {readable_pvalue(model.pvalues['z_cl'])}")
    display_residuals(model)

# Recovery rate
model_df = df.copy()
model_df['recovery'] = model_df['recovery'].astype(int)

model = smf.logit(f"recovery ~ z_cl + z_n_user_messages + gad7_start + phq9_start", data=model_df).fit()
print(model.summary())
print(f"β = {model.params['z_cl']:.2f}, 95% CI = [{model.conf_int().loc['z_cl',0]:.2f}, {model.conf_int().loc['z_cl',1]:.2f}], P = {readable_pvalue(model.pvalues['z_cl'])}")
odds_ratio = np.exp(model.params['z_cl'])
ci_lower = np.exp(model.conf_int().loc['z_cl', 0])
ci_upper = np.exp(model.conf_int().loc['z_cl', 1])
print(f"OR = {odds_ratio:.2f}, 95% CI = [{ci_lower:.2f}, {ci_upper:.2f}]")

display_residuals(model,'logistic')

# ------------------------------------------------------------------------------------------------------------------------------------
# Plot
# ------------------------------------------------------------------------------------------------------------------------------------
plot_df = df.copy()
plot_df['recovery'] = plot_df['recovery'].astype(int)

bands = {
    'low': [0,.25],
    'medium': [.25,.75],
    'high': [.75,1]
}

plot_df['cl_band'] = None
for label,band in bands.items():
    q1 = plot_df['cognitive_layer_score'].quantile(band[0])
    q2 = plot_df['cognitive_layer_score'].quantile(band[1])
    mask = (plot_df['cognitive_layer_score']>=q1) & (plot_df['cognitive_layer_score']<=q2)
    plot_df.loc[mask,'cl_band'] = label

summary = plot_df.groupby('cl_band').agg({
    'recovery': ['mean','count'],
    'cognitive_layer_score': 'mean'
}).reset_index()
summary.columns = ['cl_band','recovery','count','cognitive_layer_score']
summary['sem'] = np.sqrt(summary['recovery'] * (1 - summary['recovery']) / summary['count'])
summary = summary.sort_values(by='cognitive_layer_score')
print(summary)

fig = px.bar(
    summary,
    x='cl_band',
    y='recovery',
    error_y='sem',
    title=f"Clinical recovery",
    labels={'cl_band': 'Cognitive Layer Activation', 'recovery': 'Recovery Rate'},
    color='cl_band',
    width=400,
    height=400,
    template='simple_white',
    category_orders={'cl_band': ['low', 'medium', 'high']},
    color_discrete_map={'high': '#ff68a8', 'medium': '#FF96C3', 'low': '#ffbbd8'},
)
fig.update_yaxes(tickformat='.0%',range=[0,.6])
fig.update_layout(font=dict(family='Arial'))
fig.show()

fig.update_layout(
    showlegend=False
)
fig.write_image(f"../results/realworld_recovery.svg",width=400,height=400)

N participants = 928
Excluding 147 participants who have fewer than 2 weeks between symptom measurements
N participants = 781
--- NHS patients = 485
--- User research participants = 296
------ User research participants with 10+ weeks of data: 84

Median time between symptom measurements = 73.00 days (10.4 weeks +/ 14.7)
N conversations per participant: M = 4.3, SD = 7.4
N exchanges per conversation: M = 17.6, SD = 12.5, median = 15.0
===================================================================================================
GAD7 DELTA
===================================================================================================
                            OLS Regression Results
==============================================================================
Dep. Variable:             gad7_delta   R-squared:                       0.160
Model:                            OLS   Adj. R-squared:                  0.155
Method:                 Least Squares   F-statistic:                     36.89
Date:                Mon, 22 Sep 2025   Prob (F-statistic):           2.91e-28
Time:                        12:08:56   Log-Likelihood:                -2344.8
No. Observations:                 781   AIC:                             4700.
Df Residuals:                     776   BIC:                             4723.
Df Model:                           4
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept            -1.2158      0.596     -2.040      0.042      -2.385      -0.046
z_cl                  0.6318      0.197      3.212      0.001       0.246       1.018
z_n_user_messages    -0.1745      0.194     -0.900      0.368      -0.555       0.206
gad7_start            0.5297      0.047     11.377      0.000       0.438       0.621
phq9_start           -0.0983      0.037     -2.625      0.009      -0.172      -0.025
==============================================================================
Omnibus:                        8.347   Durbin-Watson:                   1.995
Prob(Omnibus):                  0.015   Jarque-Bera (JB):                6.172
Skew:                          -0.099   Prob(JB):                       0.0457
Kurtosis:                       2.612   Cond. No.                         71.2
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
β = 0.63, 95% CI = [0.25, 1.02], P = 0.001**

Shapiro-Wilk: 0.996, p = 0.031*
Kolmogorov-Smirnov: 0.029, p = 0.52
===================================================================================================
PHQ9 DELTA
===================================================================================================
                            OLS Regression Results
==============================================================================
Dep. Variable:             phq9_delta   R-squared:                       0.176
Model:                            OLS   Adj. R-squared:                  0.172
Method:                 Least Squares   F-statistic:                     41.43
Date:                Mon, 22 Sep 2025   Prob (F-statistic):           1.68e-31
Time:                        12:08:56   Log-Likelihood:                -2415.7
No. Observations:                 781   AIC:                             4841.
Df Residuals:                     776   BIC:                             4865.
Df Model:                           4
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept            -1.0025      0.653     -1.536      0.125      -2.283       0.278
z_cl                  0.4438      0.215      2.060      0.040       0.021       0.867
z_n_user_messages    -0.0562      0.212     -0.265      0.791      -0.473       0.360
gad7_start           -0.1120      0.051     -2.196      0.028      -0.212      -0.012
phq9_start            0.4866      0.041     11.862      0.000       0.406       0.567
==============================================================================
Omnibus:                        0.758   Durbin-Watson:                   2.046
Prob(Omnibus):                  0.684   Jarque-Bera (JB):                0.850
Skew:                          -0.056   Prob(JB):                        0.654
Kurtosis:                       2.883   Cond. No.                         71.2
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
β = 0.44, 95% CI = [0.02, 0.87], P = 0.040*

Shapiro-Wilk: 0.998, p = 0.61
Kolmogorov-Smirnov: 0.021, p = 0.87
Optimization terminated successfully.
         Current function value: 0.620754
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:               recovery   No. Observations:                  781
Model:                          Logit   Df Residuals:                      776
Method:                           MLE   Df Model:                            4
Date:                Mon, 22 Sep 2025   Pseudo R-squ.:                 0.08147
Time:                        12:08:57   Log-Likelihood:                -484.81
converged:                       True   LL-Null:                       -527.81
Covariance Type:            nonrobust   LLR p-value:                 9.304e-18
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept             1.5913      0.266      5.980      0.000       1.070       2.113
z_cl                  0.2702      0.088      3.083      0.002       0.098       0.442
z_n_user_messages     0.0080      0.194      0.041      0.967      -0.372       0.388
gad7_start           -0.0740      0.020     -3.641      0.000      -0.114      -0.034
phq9_start           -0.0696      0.017     -4.176      0.000      -0.102      -0.037
=====================================================================================
β = 0.27, 95% CI = [0.10, 0.44], P = 0.002**
OR = 1.31, 95% CI = [1.10, 1.56]

  cl_band  recovery  count  cognitive_layer_score       sem
1     low  0.328042    189               2.243386  0.034151
2  medium  0.388175    389              20.318766  0.024709
0    high  0.517241    203             131.487685  0.035072

### Supplementary: Controlling for initial state & topic complexity

In [35]:
# Read in and filter data
df = df_rw_clinical.merge(
    df_rw_pids.groupby('pid')[['cognitive_layer_score','n_user_messages']].sum().reset_index(),on='pid',how='inner'
)

mask = (df['access_time_days']>=14)
n_exclude = df.loc[~mask,'pid'].nunique()
df = df.loc[mask,].copy().reset_index(drop=True)

df['z_cl'] = zscore(np.sqrt(df['cognitive_layer_score']))
df['z_n_user_messages'] = zscore(df['n_user_messages']**2)

# ------------------------------------------------------------------------------------------------------------------------------------
# Model
# ------------------------------------------------------------------------------------------------------------------------------------

control_vars = [
    'n_words_first_message',
    'n_sentences_first_message',
    'mean_words_per_message',
    'mean_sentences_per_message',
    'dictionary_complexity',
    'embedding_entropy',
    'sentiment_polarity',
    'topic'
]

control_var_string = ' + '.join(control_vars)
control_var_string = control_var_string.replace('topic','C(topic)')

# Symptom reduction
for outcome in ['gad7_delta','phq9_delta']:

    print_title(outcome)

    model = smf.ols(f'{outcome} ~ z_cl + z_n_user_messages +gad7_start + phq9_start + {control_var_string}', data=df).fit()
    print(model.summary())
    print(f"β = {model.params['z_cl']:.2f}, 95% CI = [{model.conf_int().loc['z_cl',0]:.2f}, {model.conf_int().loc['z_cl',1]:.2f}], P = {readable_pvalue(model.pvalues['z_cl'])}")
    display_residuals(model)

# Recovery rate
model_df = df.copy()
model_df['recovery'] = model_df['recovery'].astype(int)

model = smf.logit(f"recovery ~ z_cl + z_n_user_messages + gad7_start + phq9_start + {control_var_string}", data=model_df).fit()
print(model.summary())
print(f"β = {model.params['z_cl']:.2f}, 95% CI = [{model.conf_int().loc['z_cl',0]:.2f}, {model.conf_int().loc['z_cl',1]:.2f}], P = {readable_pvalue(model.pvalues['z_cl'])}")
odds_ratio = np.exp(model.params['z_cl'])
ci_lower = np.exp(model.conf_int().loc['z_cl', 0])
ci_upper = np.exp(model.conf_int().loc['z_cl', 1])
print(f"OR = {odds_ratio:.2f}, 95% CI = [{ci_lower:.2f}, {ci_upper:.2f}]")

display_residuals(model,'logistic')

===================================================================================================
GAD7 DELTA
===================================================================================================
                            OLS Regression Results
==============================================================================
Dep. Variable:             gad7_delta   R-squared:                       0.216
Model:                            OLS   Adj. R-squared:                  0.187
Method:                 Least Squares   F-statistic:                     7.485
Date:                Mon, 22 Sep 2025   Prob (F-statistic):           3.72e-23
Time:                        12:08:58   Log-Likelihood:                -2103.1
No. Observations:                 706   AIC:                             4258.
Df Residuals:                     680   BIC:                             4377.
Df Model:                          25
Covariance Type:            nonrobust
===========================================================================================================
                                              coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------------
Intercept                                  -1.0839      1.212     -0.894      0.372      -3.464       1.297
C(topic)[T.Coping with Loss]                0.1709      1.173      0.146      0.884      -2.133       2.475
C(topic)[T.Emotional Well-being]           -0.8676      0.611     -1.420      0.156      -2.067       0.332
C(topic)[T.Family Dynamics]                 1.1580      0.857      1.352      0.177      -0.524       2.840
C(topic)[T.Financial Concerns]             -0.1337      1.292     -0.104      0.918      -2.670       2.402
C(topic)[T.Gratitude and Positivity]        0.0179      0.772      0.023      0.982      -1.498       1.533
C(topic)[T.Health Anxiety]                 -1.6747      1.825     -0.917      0.359      -5.259       1.909
C(topic)[T.Mental Health Management]       -0.8892      0.926     -0.961      0.337      -2.706       0.928
C(topic)[T.Motivation and Productivity]     1.3697      0.843      1.625      0.105      -0.286       3.025
C(topic)[T.Physical Health and Pain]       -1.9406      1.092     -1.777      0.076      -4.084       0.203
C(topic)[T.Relationship Challenges]        -0.0365      1.106     -0.033      0.974      -2.208       2.135
C(topic)[T.Self-esteem and Confidence]     -2.2739      2.244     -1.013      0.311      -6.680       2.132
C(topic)[T.Sleep Issues]                    0.2042      0.885      0.231      0.818      -1.534       1.942
C(topic)[T.Social Anxiety]                 -0.1245      1.218     -0.102      0.919      -2.516       2.267
C(topic)[T.Work and Career Stress]         -0.1917      1.066     -0.180      0.857      -2.284       1.901
z_cl                                        0.5931      0.243      2.438      0.015       0.115       1.071
z_n_user_messages                          -0.1369      0.201     -0.682      0.496      -0.531       0.257
gad7_start                                  0.5410      0.050     10.736      0.000       0.442       0.640
phq9_start                                 -0.0522      0.041     -1.268      0.205      -0.133       0.029
n_words_first_message                      -0.0239      0.017     -1.408      0.160      -0.057       0.009
n_sentences_first_message                   0.3495      0.276      1.268      0.205      -0.192       0.891
mean_words_per_message                     -0.0591      0.035     -1.666      0.096      -0.129       0.011
mean_sentences_per_message                  0.3679      0.635      0.579      0.563      -0.879       1.615
dictionary_complexity                       0.0001      0.000      0.812      0.417      -0.000       0.000
embedding_entropy                          -0.0662      0.084     -0.790      0.430      -0.231       0.098
sentiment_polarity                          0.8071      0.269      3.003      0.003       0.279       1.335
==============================================================================
Omnibus:                        5.926   Durbin-Watson:                   1.927
Prob(Omnibus):                  0.052   Jarque-Bera (JB):                4.446
Skew:                          -0.067   Prob(JB):                        0.108
Kurtosis:                       2.635   Cond. No.                     1.94e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.94e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
β = 0.59, 95% CI = [0.12, 1.07], P = 0.015*

Shapiro-Wilk: 0.996, p = 0.12
Kolmogorov-Smirnov: 0.033, p = 0.41
===================================================================================================
PHQ9 DELTA
===================================================================================================
                            OLS Regression Results
==============================================================================
Dep. Variable:             phq9_delta   R-squared:                       0.217
Model:                            OLS   Adj. R-squared:                  0.188
Method:                 Least Squares   F-statistic:                     7.539
Date:                Mon, 22 Sep 2025   Prob (F-statistic):           2.33e-23
Time:                        12:08:58   Log-Likelihood:                -2175.8
No. Observations:                 706   AIC:                             4404.
Df Residuals:                     680   BIC:                             4522.
Df Model:                          25
Covariance Type:            nonrobust
===========================================================================================================
                                              coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------------
Intercept                                  -0.2518      1.344     -0.187      0.851      -2.890       2.387
C(topic)[T.Coping with Loss]                0.2405      1.301      0.185      0.853      -2.313       2.794
C(topic)[T.Emotional Well-being]           -0.8864      0.677     -1.309      0.191      -2.216       0.443
C(topic)[T.Family Dynamics]                 0.8474      0.950      0.892      0.372      -1.017       2.712
C(topic)[T.Financial Concerns]             -0.8618      1.432     -0.602      0.547      -3.673       1.949
C(topic)[T.Gratitude and Positivity]        0.2846      0.856      0.333      0.740      -1.395       1.964
C(topic)[T.Health Anxiety]                 -0.3587      2.023     -0.177      0.859      -4.331       3.614
C(topic)[T.Mental Health Management]       -0.2730      1.026     -0.266      0.790      -2.287       1.741
C(topic)[T.Motivation and Productivity]     0.7221      0.935      0.773      0.440      -1.113       2.557
C(topic)[T.Physical Health and Pain]       -1.2859      1.210     -1.063      0.288      -3.662       1.090
C(topic)[T.Relationship Challenges]         0.4193      1.226      0.342      0.732      -1.988       2.827
C(topic)[T.Self-esteem and Confidence]      0.8995      2.488      0.362      0.718      -3.985       5.784
C(topic)[T.Sleep Issues]                   -0.6750      0.981     -0.688      0.492      -2.602       1.252
C(topic)[T.Social Anxiety]                  0.2370      1.350      0.176      0.861      -2.413       2.887
C(topic)[T.Work and Career Stress]         -0.5175      1.181     -0.438      0.661      -2.837       1.802
z_cl                                        0.4777      0.270      1.771      0.077      -0.052       1.007
z_n_user_messages                          -0.0230      0.223     -0.103      0.918      -0.460       0.414
gad7_start                                 -0.1043      0.056     -1.868      0.062      -0.214       0.005
phq9_start                                  0.5385      0.046     11.815      0.000       0.449       0.628
n_words_first_message                      -0.0127      0.019     -0.677      0.499      -0.050       0.024
n_sentences_first_message                   0.1735      0.306      0.568      0.570      -0.427       0.774
mean_words_per_message                     -0.0573      0.039     -1.458      0.145      -0.134       0.020
mean_sentences_per_message                  0.2013      0.704      0.286      0.775      -1.181       1.583
dictionary_complexity                       0.0001      0.000      0.529      0.597      -0.000       0.000
embedding_entropy                          -0.0923      0.093     -0.992      0.321      -0.275       0.090
sentiment_polarity                          0.9513      0.298      3.193      0.001       0.366       1.536
==============================================================================
Omnibus:                        0.927   Durbin-Watson:                   1.875
Prob(Omnibus):                  0.629   Jarque-Bera (JB):                1.006
Skew:                          -0.081   Prob(JB):                        0.605
Kurtosis:                       2.909   Cond. No.                     1.94e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.94e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
β = 0.48, 95% CI = [-0.05, 1.01], P = 0.08

Shapiro-Wilk: 0.999, p = 0.89
Kolmogorov-Smirnov: 0.018, p = 0.97
Optimization terminated successfully.
         Current function value: 0.605698
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:               recovery   No. Observations:                  706
Model:                          Logit   Df Residuals:                      680
Method:                           MLE   Df Model:                           25
Date:                Mon, 22 Sep 2025   Pseudo R-squ.:                 0.09569
Time:                        12:08:58   Log-Likelihood:                -427.62
converged:                       True   LL-Null:                       -472.87
Covariance Type:            nonrobust   LLR p-value:                 2.375e-09
===========================================================================================================
                                              coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------------
Intercept                                   1.0924      0.543      2.012      0.044       0.028       2.157
C(topic)[T.Coping with Loss]                0.0489      0.544      0.090      0.928      -1.017       1.115
C(topic)[T.Emotional Well-being]            0.0737      0.281      0.263      0.793      -0.476       0.624
C(topic)[T.Family Dynamics]                 0.6097      0.383      1.593      0.111      -0.141       1.360
C(topic)[T.Financial Concerns]              0.1918      0.574      0.334      0.738      -0.932       1.316
C(topic)[T.Gratitude and Positivity]        0.2751      0.347      0.792      0.429      -0.406       0.956
C(topic)[T.Health Anxiety]                 -1.2970      1.124     -1.154      0.248      -3.499       0.905
C(topic)[T.Mental Health Management]        0.3439      0.412      0.835      0.404      -0.463       1.151
C(topic)[T.Motivation and Productivity]     0.6317      0.373      1.695      0.090      -0.099       1.362
C(topic)[T.Physical Health and Pain]       -0.2635      0.513     -0.513      0.608      -1.270       0.743
C(topic)[T.Relationship Challenges]         0.3591      0.490      0.732      0.464      -0.602       1.320
C(topic)[T.Self-esteem and Confidence]     -0.6060      1.184     -0.512      0.609      -2.926       1.714
C(topic)[T.Sleep Issues]                    0.4161      0.390      1.067      0.286      -0.349       1.181
C(topic)[T.Social Anxiety]                  0.2311      0.548      0.421      0.673      -0.844       1.306
C(topic)[T.Work and Career Stress]         -0.0195      0.491     -0.040      0.968      -0.982       0.943
z_cl                                        0.3112      0.110      2.831      0.005       0.096       0.527
z_n_user_messages                          -0.0081      0.184     -0.044      0.965      -0.369       0.353
gad7_start                                 -0.0672      0.022     -2.990      0.003      -0.111      -0.023
phq9_start                                 -0.0553      0.019     -2.977      0.003      -0.092      -0.019
n_words_first_message                      -0.0032      0.009     -0.345      0.730      -0.021       0.015
n_sentences_first_message                   0.0317      0.140      0.227      0.821      -0.242       0.306
mean_words_per_message                     -0.0379      0.017     -2.286      0.022      -0.070      -0.005
mean_sentences_per_message                  0.4503      0.289      1.556      0.120      -0.117       1.017
dictionary_complexity                    5.565e-05   7.88e-05      0.706      0.480   -9.88e-05       0.000
embedding_entropy                          -0.0260      0.038     -0.681      0.496      -0.101       0.049
sentiment_polarity                          0.1874      0.121      1.547      0.122      -0.050       0.425
===========================================================================================================
β = 0.31, 95% CI = [0.10, 0.53], P = 0.005**
OR = 1.37, 95% CI = [1.10, 1.69]

## Feedback

User feedback per conversation

In [36]:
df = (
    df_rw_feedback
    .copy()
    .merge(df_rw_pids[['conversation_id','cognitive_layer_score','n_user_messages']],on='conversation_id',how='left')
)

print('Feedback per conversation:')
table = df['feedback'].value_counts().reset_index()
table.columns = ['feedback','count']
table['percent'] = table['count'] / table['count'].sum()
display(table)

# ------------------------------------------------------------------------------------------------------------------------------------
# Model
# ------------------------------------------------------------------------------------------------------------------------------------

model_df = df.copy()

model_df['feedback'] = (model_df['feedback']=='helpful').astype(int)

model_df['z_cl'] = zscore(np.sqrt(model_df['cognitive_layer_score']))
model_df['z_n_user_messages'] = zscore(model_df['n_user_messages']**2)

model = smf.logit('feedback ~ z_cl + z_n_user_messages', data=model_df).fit()
print(model.summary())
print(f"β = {model.params['z_cl']:.2f}, 95% CI = [{model.conf_int().loc['z_cl',0]:.2f}, {model.conf_int().loc['z_cl',1]:.2f}], P = {readable_pvalue(model.pvalues['z_cl'])}")
odds_ratio = np.exp(model.params['z_cl'])
ci_lower = np.exp(model.conf_int().loc['z_cl', 0])
ci_upper = np.exp(model.conf_int().loc['z_cl', 1])
print(f"OR = {odds_ratio:.2f}, 95% CI = [{ci_lower:.2f}, {ci_upper:.2f}]")

display_residuals(model,'logistic')

# ------------------------------------------------------------------------------------------------------------------------------------
# Plot
# ------------------------------------------------------------------------------------------------------------------------------------

# Top histogram
fig = px.histogram(
    df,
    x='cognitive_layer_score',
    color='feedback',
    barmode='overlay',
    title='Feedback by Cognitive Layer Score',
    width=400,
    height=250,
    color_discrete_map={
        'helpful': px.colors.qualitative.Plotly[2],
        'not helpful':px.colors.qualitative.Plotly[1]
        },
    template='simple_white',
    # histnorm='percent',
    labels={
        'cognitive_layer_score': 'Cognitive Layer Activation',
        'feedback': 'Feedback'
        },
    nbins=50,
    opacity=1
)
fig.update_yaxes(title='Conversations')
fig.update_xaxes(range=[df['cognitive_layer_score'].min(),df['cognitive_layer_score'].max()])
fig.update_layout(font={'family': 'Arial'})
fig.show()

# Bottom scatter plot
plot_df = df.groupby(['cognitive_layer_score','feedback']).size().reset_index(name='count')
plot_df['n'] = plot_df.groupby('cognitive_layer_score')['count'].transform('sum')
plot_df['p_helpful'] = plot_df['count'] / plot_df['n']
plot_df = plot_df.loc[plot_df['feedback']=='helpful',].copy().reset_index(drop=True)
plot_df['size'] = plot_df['n'].apply(lambda x: np.log(x+1))

model_df = df.copy()
model_df['feedback'] = (model_df['feedback']=='helpful').astype(int)
model = smf.logit('feedback ~ cognitive_layer_score', data=model_df).fit()

plot_df['smoothed'] = model.predict(plot_df['cognitive_layer_score'])

fig = px.scatter(
    plot_df,
    x='cognitive_layer_score',
    y='p_helpful',
    size='size',
    width=400,
    height=250,
    template='simple_white',
    color_discrete_sequence=['#EF5DA8'],
    size_max=12,
    opacity=0.4
)
fig.update_xaxes(title='Cognitive Layer Activation',range=[df['cognitive_layer_score'].min(),df['cognitive_layer_score'].max()+2])
fig.update_yaxes(title='Positive Feedback',tickformat=".0%",range=[.77,1.03])
fig.update_layout(font={'family': 'Arial'})

fig.add_trace(
    go.Scatter(
        x=plot_df['cognitive_layer_score'],
        y=plot_df['smoothed'],
        mode='lines',
        line=dict(shape='spline', color='#EF5DA8', width=2),
        fill='tozeroy',
        showlegend=False
    )
)

fig.show()

Feedback per conversation:

      feedback  count   percent
0      helpful   5700  0.869831
1  not helpful    853  0.130169

Optimization terminated successfully.
         Current function value: 0.376825
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:               feedback   No. Observations:                 6553
Model:                          Logit   Df Residuals:                     6550
Method:                           MLE   Df Model:                            2
Date:                Mon, 22 Sep 2025   Pseudo R-squ.:                 0.02556
Time:                        12:08:58   Log-Likelihood:                -2469.3
converged:                       True   LL-Null:                       -2534.1
Covariance Type:            nonrobust   LLR p-value:                 7.428e-29
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept             1.9722      0.039     50.339      0.000       1.895       2.049
z_cl                  0.7842      0.109      7.192      0.000       0.571       0.998
z_n_user_messages    -0.3901      0.111     -3.499      0.000      -0.609      -0.172
=====================================================================================
β = 0.78, 95% CI = [0.57, 1.00], P = 6.37e-13***
OR = 2.19, 95% CI = [1.77, 2.71]

Optimization terminated successfully.
         Current function value: 0.378418
         Iterations 7